domain_names:
    - sophos-email-enc-prod-us-west-2-monitor.com
    - sophos-email-enc-prod-eu-central-1-monitor.com
    - sophos-email-enc-prod-eu-west-1-monitor.com
    - sophos-email-enc-prod-us-east-2-monitor.com
#    - sophos-email-monitor.com
#    - sophos-email-monitor.org
#    - sophos-email-monitor.us
#    - sophos-email-monitor.net