domain_names:
#    - sophos-email-monitor.com
#    - sophos-email-monitor.org
#    - sophos-email-monitor.us
#    - sophos-email-monitor.net
#    - sophos-email-enc-prod-us-west-2-monitor.com
#    - sophos-email-enc-prod-eu-central-1-monitor.com
#    - sophos-email-enc-prod-eu-west-1-monitor.com
#    - sophos-email-enc-prod-us-east-2-monitor.com
    - xgemail-mf-prod-eu-c1-monitor.com
    - xgemail-mf-prod-eu-w1-monitor.com
    - xgemail-mf-prod-us-e2-monitor.com
    - xgemail-mf-prod-us-w2-monitor.com