az:
  a: us-west-2a
  b: us-west-2b
  c: us-west-2c

aws:
  asg:
    cd:
      as_min_size:                              "1"
      as_max_size:                              "18"
      cron_scale_in:                            "00 02 * * 1-5"
      cron_scale_out:                           "30 14 * * 1-5"
      on_hour_desired:                          "2"
      scale_in_out_weekdays:                    "true"

    is:
      as_min_size:                              "1"
      as_max_size:                              "18"
      cron_scale_in:                            "00 02 * * 1-5"
      cron_scale_out:                           "30 14 * * 1-5"
      on_hour_desired:                          "2"
      scale_in_out_weekdays:                    "true"
      smtpd_auth_xcli_hosts:                    "87.229.68.231"