az:
  a: eu-central-1a
  b: eu-central-1b
  c: eu-central-1c

xgemail_sxl_dbl: uri.ire2.sophosxl.com
xgemail_sxl_rbl: fur.ire2.sophosxl.com

asg:
  cd:
    as_min_size:                              "1"
    as_max_size:                              "6"
    cron_scale_in:                            "00 17 * * 1-5"
    cron_scale_out:                           "30 05 * * 1-5"
    on_hour_desired:                          "3"
    scale_in_out_weekdays:                    "true"

  is:
    as_min_size:                              "1"
    as_max_size:                              "6"
    cron_scale_in:                            "00 17 * * 1-5"
    cron_scale_out:                           "30 05 * * 1-5"
    on_hour_desired:                          "1"
    scale_in_out_weekdays:                    "true"