domain_names:
#    - sophos-email-qa-us-west-2-monitor.com
#    - sophos-email-qa-eu-central-1-monitor.com
#    - sophos-email-qa-eu-west-1-monitor.com
#    - sophos-email-qa-us-east-2-monitor.com
#    - sophos-email-enc-qa-us-west-2-monitor.com
#    - sophos-email-enc-qa-eu-central-1-monitor.com
#    - sophos-email-enc-qa-eu-west-1-monitor.com
#    - sophos-email-enc-qa-us-east-2-monitor.com
    - xgemail-mf-qa-eu-c1-monitor.com
    - xgemail-mf-qa-eu-w1-monitor.com
    - xgemail-mf-qa-us-e2-monitor.com
    - xgemail-mf-qa-us-w2-monitor.com