---
- name: "Deploy {{stack.ec2.elb.cs}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.ec2.elb.cs}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.ec2.elb.elb_public_xgemail_template}}"
    template_parameters:
      Branch:                         "{{build.branch}}"
      Environment:                    "{{account.name}}"
      ExternalPort:                   "25"
      ExternalAlternatePort:          "587"
      HealthCheckInterval:            "60"
      HealthCheckTarget:              "TCP:25"
      HealthCheckUnhealthyThreshold:  "10"
      HostAlarmTopicARN:              "{{sns.arn_prefix}}{{sns.alarm_sns_topic}}"
      LoadBalancerName:               "{{ec2.elb.cs}}"
      SecurityGroupLb:                "{{cloud_email_sg_output.ansible_facts.cloudformation[stack.ec2.sg.cloud_email_security_groups].stack_outputs.XgemailCustomerSubmitSecurityGroupLb}}"
      Subnets:                        "{{cloud_email_vpc_output.ansible_facts.cloudformation[stack.vpc.cloud_email_vpc].stack_outputs.VpcZoneIdentifiersPublic}}"
      TagApplication:                 "customer-submit"
      Vpc:                            "{{cloud_email_vpc_output.ansible_facts.cloudformation[stack.vpc.cloud_email_vpc].stack_outputs.Vpc}}"
  register: elb_stack_output

- debug:
    var: elb_stack_output
    verbosity: 3

- name: "Display ELB Stack Output"
  debug:
    msg: "{{elb_stack_output.stack_outputs}}"
    verbosity: 2