---
aws_account_id:                             "382702281923"
eu_central_1_hostedZoneName:                "sophos-email-qa-eu-central-1-monitor.com"
eu_central_1_resourceRecords:               "10 mx-01-eu-central-1.qa.hydra.sophos.com.,20 mx-02-eu-central-1.qa.hydra.sophos.com."
eu_west_1_hostedZoneName:                   "sophos-email-qa-eu-west-1-monitor.com"
eu_west_1_resourceRecords:                  "10 mx-01-eu-west-1.qa.hydra.sophos.com.,20 mx-02-eu-west-1.qa.hydra.sophos.com."
us_east_2_hostedZoneName:                   "sophos-email-qa-us-east-2-monitor.com"
us_east_2_resourceRecords:                  "10 mx-01-us-east-2.qa.hydra.sophos.com.,20 mx-02-us-east-2.qa.hydra.sophos.com."
us_west_2_hostedZoneName:                   "sophos-email-qa-us-west-2-monitor.com"
us_west_2_resourceRecords:                  "10 mx-01-us-west-2.qa.hydra.sophos.com.,20 mx-02-us-west-2.qa.hydra.sophos.com."
us_west_2_recipient_hostedZoneName:         "sophos-email-qa-us-west-2-recipient.com"
us_west_2_recipient_resourceRecords:        "10 inbound-smtp.qa.us-west-2.amazonaws.com."
eu_central_1_mailbox_name:                  "eu.central.1.qa@sophos-email-qa-eu-central-1-monitor.com"
eu_west_1_mailbox_name:                     "eu.west.1.qa@sophos-email-qa-eu-west-1-monitor.com"
us_east_2_mailbox_name:                     "us.east.2.qa@sophos-email-qa-us-east-2-monitor.com"
us_west_2_mailbox_name:                     "us.west.2.qa@sophos-email-qa-us-west-2-monitor.com"
us_west_2_sender_mailbox_name:              "monitor.sender@sophos-email-qa-us-west-2-monitor.com"
eu_central_1_id:                            "001b900d-0451-4570-8877-90924123080a"
eu_central_1_private_key:                   "sophos-email-qa-eu-central-1-monitor.com.key"
eu_central_1_public_key:                    "sophos-email-qa-eu-central-1-monitor.com.crt"
eu_central_1_public_thumb_print:            "sophos-email-qa-eu-central-1-monitor.com_sha1.txt"
eu_west_1_id:                               "0a3fb2ec-4b33-4f62-a9d1-247b0074e222"
eu_west_1_private_key:                      "sophos-email-qa-eu-west-1-monitor.com.key"
eu_west_1_public_key:                       "sophos-email-qa-eu-west-1-monitor.com.crt"
eu_west_1_public_thumb_print:               "sophos-email-qa-eu-west-1-monitor.com_sha1.txt"
tenant_id:                                  "baf0da6e-b644-43a5-98a8-e14ed39b8d02"
us_east_2_id:                               "e70d388a-d489-4feb-a7f7-4827e07843bb"
us_east_2_private_key:                      "sophos-email-qa-us-east-2-monitor.com.key"
us_east_2_public_key:                       "sophos-email-qa-us-east-2-monitor.com.crt"
us_east_2_public_thumb_print:               "sophos-email-qa-us-east-2-monitor.com_sha1.txt"
us_west_2_id:                               "d72166b2-4c93-411a-9e64-8bc3b0c9b6cc"
us_west_2_private_key:                      "sophos-email-qa-us-west-2-monitor.com.key"
us_west_2_public_key:                       "sophos-email-qa-us-west-2-monitor.com.crt"
us_west_2_public_thumb_print:               "sophos-email-qa-us-west-2-monitor.com_sha1.txt"
ses_rule_set_name:                          "tf-phish-inbox-receiving"
ses_region:                                 "us-west-2"
eu_central_1a_cidr:                         "52.28.34.203/32"
eu_central_1b_cidr:                         "52.29.254.175/32"
eu_west_1a_cidr:                            "52.208.86.71/32"
eu_west_1b_cidr:                            "52.208.49.128/32"
us_east_2a_cidr:                            "13.58.247.170/32"
us_east_2b_cidr:                            "18.221.162.5/32"
us_west_2a_cidr:                            "52.41.209.27/32"
us_west_2b_cidr:                            "52.25.46.198/32"
inbound_mail_recipients:                    "us.west.2.qa@sophos-email-qa-us-west-2-monitor.com, eu.central.1.qa@sophos-email-qa-eu-central-1-monitor.com, eu.west.1.qa@sophos-email-qa-eu-west-1-monitor.com, us.east.2.qa@sophos-email-qa-us-east-2-monitor.com"
outbound_mail_recipients:                   "sophos-email-qa-us-west-2-recipient.com, monitor.recipient@sophos-email-qa-us-west-2-recipient.com"
domains:                                    "sophos-email-qa-eu-central-1-monitor.com, sophos-email-qa-us-west-2-monitor.com, sophos-email-qa-eu-west-1-monitor.com, sophos-email-qa-us-east-2-monitor.com, sophos-email-qa-us-west-2-recipient.com, sophos-email-qa-enc-eu-central-1-monitor.com, sophos-email-qa-encryption-us-west-2-monitor.com, sophos-email-qa-encryption-eu-west-1-monitor.com, sophos-email-qa-encryption-us-east-2-monitor.com, sophos-email-qa-encryption-us-west-2-recipient.com, sophos-email-ms-qa-eu-west-1-monitor.com, sophos-email-ms-qa-eu-central-1-monitor.com, sophos-email-ms-qa-us-west-2-monitor.com"

enc:
  eu_central_1_hostedZoneName:                "sophos-email-qa-enc-eu-central-1-monitor.com"
  eu_central_1_resourceRecords:               "10 mx-01-eu-central-1.qa.hydra.sophos.com.,20 mx-02-eu-central-1.qa.hydra.sophos.com."
  eu_west_1_hostedZoneName:                   "sophos-email-qa-encryption-eu-west-1-monitor.com"
  eu_west_1_resourceRecords:                  "10 mx-01-eu-west-1.qa.hydra.sophos.com.,20 mx-02-eu-west-1.qa.hydra.sophos.com."
  us_east_2_hostedZoneName:                   "sophos-email-qa-encryption-us-east-2-monitor.com"
  us_east_2_resourceRecords:                  "10 mx-01-us-east-2.qa.hydra.sophos.com.,20 mx-02-us-east-2.qa.hydra.sophos.com."
  us_west_2_hostedZoneName:                   "sophos-email-qa-encryption-us-west-2-monitor.com"
  us_west_2_resourceRecords:                  "10 mx-01-us-west-2.qa.hydra.sophos.com.,20 mx-02-us-west-2.qa.hydra.sophos.com."
  us_west_2_recipient_hostedZoneName:         "sophos-email-qa-encryption-us-west-2-recipient.com"
  us_west_2_recipient_resourceRecords:        "10 inbound-smtp.qa.us-west-2.amazonaws.com."
  eu_central_1_mailbox_name:                  "eu-central-1-encryption@sophos-email-qa-enc-eu-central-1-monitor.com"
  eu_west_1_mailbox_name:                     "eu-west-1-encryption@sophos-email-qa-encryption-eu-west-1-monitor.com"
  us_east_2_mailbox_name:                     "us-east-2-encryption@sophos-email-qa-encryption-us-east-2-monitor.com"
  us_west_2_mailbox_name:                     "us-west-2-encryption@sophos-email-qa-encryption-us-west-2-monitor.com"
  eu_central_1_id:                            "f8744bbc-1745-4266-a9d6-0e29e7c0e42e"
  eu_central_1_private_key:                   "sophos-email-qa-enc-eu-central-1-monitor.com.key"
  eu_central_1_public_key:                    "sophos-email-qa-enc-eu-central-1-monitor.com.crt"
  eu_central_1_public_thumb_print:            "sophos-email-qa-enc-eu-central-1-monitor.com_sha1.txt"
  eu_west_1_id:                               "890b6436-e2f5-4195-ba8f-1583f614ad38"
  eu_west_1_private_key:                      "sophos-email-qa-encryption-eu-west-1-monitor.com.key"
  eu_west_1_public_key:                       "sophos-email-qa-encryption-eu-west-1-monitor.com.crt"
  eu_west_1_public_thumb_print:               "sophos-email-qa-encryption-eu-west-1-monitor.com_sha1.txt"
  us_east_2_id:                               "020b6824-9163-4f87-a4cf-0e22fad7b04b"
  us_east_2_private_key:                      "sophos-email-qa-encryption-us-east-2-monitor.com.key"
  us_east_2_public_key:                       "sophos-email-qa-encryption-us-east-2-monitor.com.crt"
  us_east_2_public_thumb_print:               "sophos-email-qa-encryption-us-east-2-monitor.com_sha1.txt"
  us_west_2_id:                               "f3437f11-46f0-45d8-ba69-06714a7a31b4"
  us_west_2_private_key:                      "sophos-email-qa-encryption-us-west-2-monitor.com.key"
  us_west_2_public_key:                       "sophos-email-qa-encryption-us-west-2-monitor.com.crt"
  us_west_2_public_thumb_print:               "sophos-email-qa-encryption-us-west-2-monitor.com_sha1.txt"
  encryption_outbound_mail_recipients:        "sophos-email-qa-encryption-us-west-2-recipient.com, monitor.recipient@sophos-email-qa-encryption-us-west-2-recipient.com"

ms:
  eu_west_1_mailbox_name:                     "eu.west.1.qa@sophos-email-ms-qa-eu-west-1-monitor.com"
  eu_central_1_mailbox_name:                  "eu.central.1.qa@sophos-email-ms-qa-eu-central-1-monitor.com"
  us_east_2_mailbox_name:                     "us.e2.qa@sophos-email-ms-qa-us-east-2-monitor.com"
  us_west_2_mailbox_name:                     "us.west.2.qa@sophos-email-ms-qa-us-west-2-monitor.com"
  us_west_2_sender_mailbox_name:              "monitor.sender@sophos-email-ms-qa-us-west-2-monitor.com"
  eu_west_1_hostedZoneName:                   "sophos-email-ms-qa-eu-west-1-monitor.com"
  eu_west_1_resourceRecords:                  "10 mx-01-eu-west-1.qa.hydra.sophos.com.,20 mx-02-eu-west-1.qa.hydra.sophos.com."
  eu_central_1_hostedZoneName:                "sophos-email-ms-qa-eu-central-1-monitor.com"
  eu_central_1_resourceRecords:               "10 mx-01-eu-central-1.qa.hydra.sophos.com.,20 mx-02-eu-central-1.qa.hydra.sophos.com."
  us_east_2_hostedZoneName:                   "sophos-email-ms-qa-eu-central-1-monitor.com"
  us_east_2_resourceRecords:                  "10 mx-01-eu-central-1.qa.hydra.sophos.com.,20 mx-02-eu-central-1.qa.hydra.sophos.com."
  us_west_2_hostedZoneName:                   "sophos-email-ms-qa-us-west-2-monitor.com"
  us_west_2_resourceRecords:                  "10 mx-01-us-west-2.qa.hydra.sophos.com.,20 mx-02-us-west-2.qa.hydra.sophos.com."
  inbound_ms_mail_recipients:                 "eu.west.1.qa@sophos-email-ms-qa-eu-west-1-monitor.com, eu.central.1.qa@sophos-email-ms-qa-eu-central-1-monitor.com, us.west.2.qa@sophos-email-ms-qa-us-west-2-monitor.com"

mf:
  eu_central_1_hostedZoneName:                "xgemail-mf-qa-eu-c1-monitor.com"
  eu_central_1_resourceRecords:               "10 mx-01-eu-central-1.qa.hydra.sophos.com.,20 mx-02-eu-central-1.qa.hydra.sophos.com."
  us_west_2_hostedZoneName:                   "xgemail-mf-qa-us-w2-monitor.com"
  us_west_2_resourceRecords:                  "10 mx-01-us-west-2.qa.hydra.sophos.com.,20 mx-02-us-west-2.qa.hydra.sophos.com."
  us_west_2_recipient_hostedZoneName:         "xgemail-mf-qa-us-w2-monitor.com"
  us_west_2_recipient_resourceRecords:        "10 inbound-smtp.qa.us-west-2.amazonaws.com."
  eu_central_1_mailbox_name:                  "mailflow-euc1@xgemail-mf-qa-eu-c1-monitor.com"
  us_west_2_mailbox_name:                     "mailflow-usw2@xgemail-mf-qa-us-w2-monitor.com"
  eu_central_1_id:                            "3268d575-4524-4373-8e0c-bbc1e087bc26"
  eu_central_1_private_key:                   "xgemail-mf-qa-eu-c1-monitor.com.key"
  eu_central_1_public_key:                    "xgemail-mf-qa-eu-c1-monitor.com.crt"
  eu_central_1_public_thumb_print:            "xgemail-mf-qa-eu-c1-monitor.com_sha1.txt"
  us_west_2_id:                               "0408e299-4578-4882-9d9b-60e58b6fe33a"
  us_west_2_private_key:                      "xgemail-mf-qa-us-w2-monitor.com.key"
  us_west_2_public_key:                       "xgemail-mf-qa-us-w2-monitor.com.crt"
  us_west_2_public_thumb_print:               "xgemail-mf-qa-us-w2-monitor.com_sha1.txt"
  mf_outbound_mail_recipients:                "xgemail-mf-qa-us-w2-monitor.com, monitor.recipient@xgemail-mf-qa-us-w2-monitor.com"
  inbound_mf_mail_recipients:                 "mailflow-euc1@xgemail-mf-qa-eu-c1-monitor.com, mailflow-usw2@xgemail-mf-qa-us-w2-monitor.com"

