aws:
  asg:
    cd:
      as_min_size:                              "0"
      as_max_size:                              "0"
    cs:
      as_min_size:                              "0"
      as_max_size:                              "0"
    cx:
      asg_min_size:                             [0,0,0]
    ed:
      as_min_size:                              "0"
      as_max_size:                              "0"
    is:
      as_min_size:                              "0"
      as_max_size:                              "0"
    id:
      as_min_size:                              "0"
      as_max_size:                              "0"
    ix:
      asg_min_size:                             [0,0,0,0]
    rd:
      as_min_size:                              "0"
      as_max_size:                              "0"
    rx:
      asg_min_size:                             [0,0,0]

az:
  a: us-east-2a
  b: us-east-2b
  c: us-east-2c